-- Clear existing data
TRUNCATE TABLE "player_responses" CASCADE;
TRUNCATE TABLE "card_responses" CASCADE;
TRUNCATE TABLE "cards" CASCADE;
TRUNCATE TABLE "categories" CASCADE;
TRUNCATE TABLE "color_presets" CASCADE;
TRUNCATE TABLE "players" CASCADE;
TRUNCATE TABLE "game_sessions" CASCADE;
TRUNCATE TABLE "users" CASCADE;
