import type { Metadata } from "next";
import { Geist, Geist_Mono, Russo_One, Roboto_Condensed } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../contexts/ThemeContext";
import { ToastProvider } from "@/components/ui/Toast";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const russo = Russo_One({
    weight: "400",
    variable: "--font-russo",
    subsets: ["latin"],
});

const roboto = Roboto_Condensed({
    weight: ["300", "400", "700"],
    variable: "--font-roboto",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Crisis Card Game",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${russo.variable} ${roboto.variable} antialiased`}
            >
                <ThemeProvider>
                    <ToastProvider>
                        {children}
                    </ToastProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
