import type { Metadata } from "next";
import { Geist, Geist_Mono, Russo_One, Roboto_Condensed, Pixelify_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "../contexts/ThemeContext";
import { ToastProvider } from "@/components/ui/Toast";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const russo = Russo_One({
    weight: "400",
    variable: "--font-russo",
    subsets: ["latin"],
});

const roboto = Roboto_Condensed({
    weight: ["300", "400", "700"],
    variable: "--font-roboto",
    subsets: ["latin"],
});

const pixelify = Pixelify_Sans({
    weight: ["400", "500", "600", "700"],
    variable: "--font-pixel",
    subsets: ["latin"],
    display: "swap"
});

const nohemi = localFont({
    src: "../../public/fonts/Nohemi-VF-BF6438cc58ad63d.ttf",
    variable: "--font-nohemi",
    display: "swap",
});

const perfectlyNostalgic = localFont({
    src: [
        {
            path: "../../public/fonts/perfectly_nostalgic-BF6495169fede88.ttf",
            weight: "400",
            style: "normal",
        },
        {
            path: "../../public/fonts/perfectly_nostalgic_italic-BF649516a085a69.ttf",
            weight: "400",
            style: "italic",
        },
        {
            path: "../../public/fonts/perfectly_nostalgic_bold-BF649516a0920d1.ttf",
            weight: "700",
            style: "normal",
        },
        {
            path: "../../public/fonts/perfectly_nostalgic_bold_italic-BF649516a0b32b6.ttf",
            weight: "700",
            style: "italic",
        },
    ],
    variable: "--font-perfectly-nostalgic",
    display: "swap",
});

export const metadata: Metadata = {
    title: "Crisis Card Game",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${russo.variable} ${roboto.variable} ${nohemi.variable} ${perfectlyNostalgic.variable} ${pixelify.variable} antialiased`}
            >
                <ThemeProvider>
                    <ToastProvider>
                        {children}
                    </ToastProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
